---
- name: Ensure that Nginx is installed
  apt:
    name: nginx
    state: latest

- name: Copy the Nginx configuration file
  template:
    src: dsm.cfg.j2
    dest: /etc/nginx/sites-available/default
    mode: 0644
  notify: Restart Nginx

- name: Copy DSM static files to the remote server
  copy:
    src: dsm
    dest: /var/www
    owner: www-data
    group: www-data
    mode: '0660'

- name: Ensure that Nginx is started and enabled on boot
  service:
    name: nginx
    state: started
    enabled: yes
