- name: Get all hosts information
  hosts: redis # all
  gather_facts: yes
  tasks:
    - debug:
        msg:
          - 'Hostname: {{ ansible_hostname }}'
          - 'External IP: {{ inventory_hostname }}'
          - 'Private IP: {{ ansible_default_ipv4.address }}'

- name: Update, Upgrade and install packages.
  hosts: all
  gather_facts: no
  become: yes
  roles:
    - role: packages

- name: Installing Nginx
  hosts: nginx
  become: yes
  roles:
    - role: nginx
      vars:
        server_name: '{{ inventory_hostname }}'
        listen_port: 80

- name: Installing HAproxy
  hosts: haproxy
  become: yes
  gather_facts: yes
  roles:
    - role: haproxy
      vars:
        maxconn: 1024
        bind_address: '*' # "{{ hostvars[groups['nginx'][0]]['ansible_default_ipv4']['address'] }}"
        app_servers_listen_port: 8080
        app_servers_addresses: "{{ groups['appServers'] }}"

- name: Installing MySQL
  hosts: mysql
  become: yes
  roles:
    - role: mysql
      vars:
        mysql_port: '3306'
        mysql_bind_address: '0.0.0.0'
        mysql_user_home: /root
        mysql_user_name: root
        mysql_user_password: root
        mysql_root_password_update: false

    - role: mysql-dsm
      vars:
        dsm_user: 'dsm'
        dsm_password: 'dsm2019EA!'
        dsm_network: '10.128.0.%'
        dsm_database_name: 'dsm'

- name: Installing Redis
  hosts: redis
  become: yes
  roles:
    - role: redis
      vars:
        redis_port: 6379
        redis_bind_interface: '0.0.0.0'
        redis_requirepass: 'dsm2019EA!'
