version: '3.5'

# ---------------------------
# DSM containers network
# ---------------------------
networks:
  dsmNetwork:
    name: dsm-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24

# ---------------------------
# DSM containers
# ---------------------------
services:
  # Load Balancer
  haproxy:
    build: ./haproxy
    image: dsm-haproxy
    container_name: dsm-haproxy
    networks:
      dsmNetwork:
        ipv4_address: 10.1.0.10
    ports:
      - '80:80'

  # Web Server 1 (Nginx)
  webserver1:
    build: ./webServer1
    image: dsm-ws1
    container_name: dsm-ws1
    networks:
      dsmNetwork:
        ipv4_address: 10.1.0.100
    ports:
      - '8080:80'

  # Application Server 1
  appServer1:
    build: ./appServer1
    image: dsm-ap1
    container_name: dsm-ap1
    networks:
      dsmNetwork:
        ipv4_address: 10.1.0.101
    ports:
      - '8081:8080'

  # Web Server 2 (Nginx)
  webserver2:
    build: ./webServer2
    image: dsm-ws2
    container_name: dsm-ws2
    networks:
      dsmNetwork:
        ipv4_address: 10.1.0.200
    ports:
      - '8082:80'

  # Application Server 2
  appServer2:
    build: ./appServer2
    image: dsm-ap2
    container_name: dsm-ap2
    networks:
      dsmNetwork:
        ipv4_address: 10.1.0.201
    ports:
      - '8083:8080'
