---
## General

wildfly_version: '17.0.0.Final'

## Service options

# Owner
wildfly_user: wildfly
wildfly_group: wildfly
wildfly_user_home: '/home/{{ wildfly_user }}'
wildfly_user_shell: '/bin/sh'
wildfly_user_uid: 1005

# start on boot
wildfly_service_enabled: True
# current state: started, stopped
wildfly_service_state: started

# Files & Paths
wildfly_conf_path: '/etc/wildfly'
wildfly_install_path: '/opt'
wildfly_home_path: '{{ wildfly_install_path }}/wildfly'
wildfly_log_file_path: '{{ wildfly_home_path }}/standalone/log'
wildfly_running_configuration_file: '{{ wildfly_home_path }}/bin/standalone.conf'

# Allowing playbooks to provide external config files&templates
wildfly_extra_conf_path: '{{ playbook_dir }}/files/wildfly/conf'
wildfly_extra_conf_template_path: '{{ playbook_dir }}/templates/wildfly/conf'

# Log
wildfly_log_file_name: server.log
wildfly_log_console_enabled: 'false'
wildfly_log_console_level: INFO
wildfly_log_file_enabled: 'true'
wildfly_log_file_level: INFO
wildfly_log_file_rotatesize: 1024000
wildfly_log_file_maxBackupIndex: 7

# Network
wildfly_bind: 0.0.0.0

# Management
wildfly_management_users: []
